# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from stepper_motor/StepperConfig.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class StepperConfig(genpy.Message):
  _md5sum = "ff43d43f44d3ccbde0bc997af21c6851"
  _type = "stepper_motor/StepperConfig"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float32 speed
float32 max_speed
float32 min_speed
float32 accel
float32 deccel
uint8 step_pin
uint8 dir_pin
int64 steps_per_rev


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','speed','max_speed','min_speed','accel','deccel','step_pin','dir_pin','steps_per_rev']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','uint8','uint8','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,speed,max_speed,min_speed,accel,deccel,step_pin,dir_pin,steps_per_rev

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StepperConfig, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.speed is None:
        self.speed = 0.
      if self.max_speed is None:
        self.max_speed = 0.
      if self.min_speed is None:
        self.min_speed = 0.
      if self.accel is None:
        self.accel = 0.
      if self.deccel is None:
        self.deccel = 0.
      if self.step_pin is None:
        self.step_pin = 0
      if self.dir_pin is None:
        self.dir_pin = 0
      if self.steps_per_rev is None:
        self.steps_per_rev = 0
    else:
      self.header = std_msgs.msg.Header()
      self.speed = 0.
      self.max_speed = 0.
      self.min_speed = 0.
      self.accel = 0.
      self.deccel = 0.
      self.step_pin = 0
      self.dir_pin = 0
      self.steps_per_rev = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5f2Bq().pack(_x.speed, _x.max_speed, _x.min_speed, _x.accel, _x.deccel, _x.step_pin, _x.dir_pin, _x.steps_per_rev))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.speed, _x.max_speed, _x.min_speed, _x.accel, _x.deccel, _x.step_pin, _x.dir_pin, _x.steps_per_rev,) = _get_struct_5f2Bq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5f2Bq().pack(_x.speed, _x.max_speed, _x.min_speed, _x.accel, _x.deccel, _x.step_pin, _x.dir_pin, _x.steps_per_rev))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.speed, _x.max_speed, _x.min_speed, _x.accel, _x.deccel, _x.step_pin, _x.dir_pin, _x.steps_per_rev,) = _get_struct_5f2Bq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_5f2Bq = None
def _get_struct_5f2Bq():
    global _struct_5f2Bq
    if _struct_5f2Bq is None:
        _struct_5f2Bq = struct.Struct("<5f2Bq")
    return _struct_5f2Bq
