(cl:defpackage stepper_motor-msg
  (:use )
  (:export
   "<LINEARSTEPPERCONFIG>"
   "LINEARSTEPPERCONFIG"
   "<LINEARSTEPPERCONFIG>"
   "LINEARSTEPPERCONFIG"
   "<LINEARSTEPPERMOVE>"
   "LINEARSTEPPERMOVE"
   "<LINEARSTEPPERMOVE>"
   "LINEARSTEPPERMOVE"
   "<STEPPERCONFIG>"
   "STEPPERCONFIG"
   "<STEPPERCONFIG>"
   "STEPPERCONFIG"
   "<STEPPERMOVE>"
   "STEPPERMOVE"
   "<STEPPERMOVE>"
   "STEPPERMOVE"
  ))

