(cl:defpackage stepper_motor-msg
  (:use )
  (:export
   "<ABSOLUTEMOVE>"
   "ABSOLUTEMOVE"
   "<CARTESIANMOVE>"
   "CARTESIANMOVE"
   "<LINEARABSOLUTEMOVE>"
   "LINEARABSOLUTEMOVE"
   "<RELATIVEMOVE>"
   "RELATIVEMOVE"
   "<STEPPERCONFIG>"
   "STEPPERCONFIG"
   "<POSITION_MSG>"
   "POSITION_MSG"
  ))

