// Generated by gencpp from file cartesian_controller/CartesianMove.msg
// DO NOT EDIT!


#ifndef CARTESIAN_CONTROLLER_MESSAGE_CARTESIANMOVE_H
#define CARTESIAN_CONTROLLER_MESSAGE_CARTESIANMOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <stepper_motor/AbsoluteMove.h>
#include <stepper_motor/AbsoluteMove.h>
#include <stepper_motor/AbsoluteMove.h>

namespace cartesian_controller
{
template <class ContainerAllocator>
struct CartesianMove_
{
  typedef CartesianMove_<ContainerAllocator> Type;

  CartesianMove_()
    : header()
    , x()
    , y()
    , z()  {
    }
  CartesianMove_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::stepper_motor::AbsoluteMove_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::stepper_motor::AbsoluteMove_<ContainerAllocator>  _y_type;
  _y_type y;

   typedef  ::stepper_motor::AbsoluteMove_<ContainerAllocator>  _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::cartesian_controller::CartesianMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartesian_controller::CartesianMove_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianMove_

typedef ::cartesian_controller::CartesianMove_<std::allocator<void> > CartesianMove;

typedef boost::shared_ptr< ::cartesian_controller::CartesianMove > CartesianMovePtr;
typedef boost::shared_ptr< ::cartesian_controller::CartesianMove const> CartesianMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartesian_controller::CartesianMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartesian_controller::CartesianMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cartesian_controller::CartesianMove_<ContainerAllocator1> & lhs, const ::cartesian_controller::CartesianMove_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cartesian_controller::CartesianMove_<ContainerAllocator1> & lhs, const ::cartesian_controller::CartesianMove_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cartesian_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cartesian_controller::CartesianMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartesian_controller::CartesianMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_controller::CartesianMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_controller::CartesianMove_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_controller::CartesianMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_controller::CartesianMove_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartesian_controller::CartesianMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "168cb11f321e52482a5826f10f646af5";
  }

  static const char* value(const ::cartesian_controller::CartesianMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x168cb11f321e5248ULL;
  static const uint64_t static_value2 = 0x2a5826f10f646af5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartesian_controller::CartesianMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartesian_controller/CartesianMove";
  }

  static const char* value(const ::cartesian_controller::CartesianMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartesian_controller::CartesianMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"stepper_motor/AbsoluteMove x\n"
"stepper_motor/AbsoluteMove y\n"
"stepper_motor/AbsoluteMove z\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: stepper_motor/AbsoluteMove\n"
"Header header\n"
"int64 abs_position\n"
"int64 speed\n"
;
  }

  static const char* value(const ::cartesian_controller::CartesianMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartesian_controller::CartesianMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartesian_controller::CartesianMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartesian_controller::CartesianMove_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    s << std::endl;
    Printer< ::stepper_motor::AbsoluteMove_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::stepper_motor::AbsoluteMove_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    s << std::endl;
    Printer< ::stepper_motor::AbsoluteMove_<ContainerAllocator> >::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTESIAN_CONTROLLER_MESSAGE_CARTESIANMOVE_H
