// Generated by gencpp from file stepper_motor/LinearStepperMove.msg
// DO NOT EDIT!


#ifndef STEPPER_MOTOR_MESSAGE_LINEARSTEPPERMOVE_H
#define STEPPER_MOTOR_MESSAGE_LINEARSTEPPERMOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace stepper_motor
{
template <class ContainerAllocator>
struct LinearStepperMove_
{
  typedef LinearStepperMove_<ContainerAllocator> Type;

  LinearStepperMove_()
    : header()
    , position(0.0)
    , speed(0.0)
    , move_type()
    , units()  {
    }
  LinearStepperMove_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(0.0)
    , speed(0.0)
    , move_type(_alloc)
    , units(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _position_type;
  _position_type position;

   typedef float _speed_type;
  _speed_type speed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _move_type_type;
  _move_type_type move_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _units_type;
  _units_type units;





  typedef boost::shared_ptr< ::stepper_motor::LinearStepperMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stepper_motor::LinearStepperMove_<ContainerAllocator> const> ConstPtr;

}; // struct LinearStepperMove_

typedef ::stepper_motor::LinearStepperMove_<std::allocator<void> > LinearStepperMove;

typedef boost::shared_ptr< ::stepper_motor::LinearStepperMove > LinearStepperMovePtr;
typedef boost::shared_ptr< ::stepper_motor::LinearStepperMove const> LinearStepperMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stepper_motor::LinearStepperMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stepper_motor::LinearStepperMove_<ContainerAllocator1> & lhs, const ::stepper_motor::LinearStepperMove_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.speed == rhs.speed &&
    lhs.move_type == rhs.move_type &&
    lhs.units == rhs.units;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stepper_motor::LinearStepperMove_<ContainerAllocator1> & lhs, const ::stepper_motor::LinearStepperMove_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stepper_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stepper_motor::LinearStepperMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_motor::LinearStepperMove_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_motor::LinearStepperMove_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1db798ee9f66ea3cd530d4730e75a01d";
  }

  static const char* value(const ::stepper_motor::LinearStepperMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1db798ee9f66ea3cULL;
  static const uint64_t static_value2 = 0xd530d4730e75a01dULL;
};

template<class ContainerAllocator>
struct DataType< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stepper_motor/LinearStepperMove";
  }

  static const char* value(const ::stepper_motor::LinearStepperMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 position\n"
"float32 speed\n"
"string move_type\n"
"string units\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::stepper_motor::LinearStepperMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.speed);
      stream.next(m.move_type);
      stream.next(m.units);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinearStepperMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stepper_motor::LinearStepperMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stepper_motor::LinearStepperMove_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "move_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.move_type);
    s << indent << "units: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.units);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEPPER_MOTOR_MESSAGE_LINEARSTEPPERMOVE_H
