// Generated by gencpp from file stepper_motor/RelativeMove.msg
// DO NOT EDIT!


#ifndef STEPPER_MOTOR_MESSAGE_RELATIVEMOVE_H
#define STEPPER_MOTOR_MESSAGE_RELATIVEMOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace stepper_motor
{
template <class ContainerAllocator>
struct RelativeMove_
{
  typedef RelativeMove_<ContainerAllocator> Type;

  RelativeMove_()
    : header()
    , rel_steps(0)
    , speed(0)  {
    }
  RelativeMove_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rel_steps(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _rel_steps_type;
  _rel_steps_type rel_steps;

   typedef int64_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::stepper_motor::RelativeMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stepper_motor::RelativeMove_<ContainerAllocator> const> ConstPtr;

}; // struct RelativeMove_

typedef ::stepper_motor::RelativeMove_<std::allocator<void> > RelativeMove;

typedef boost::shared_ptr< ::stepper_motor::RelativeMove > RelativeMovePtr;
typedef boost::shared_ptr< ::stepper_motor::RelativeMove const> RelativeMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stepper_motor::RelativeMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stepper_motor::RelativeMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stepper_motor::RelativeMove_<ContainerAllocator1> & lhs, const ::stepper_motor::RelativeMove_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rel_steps == rhs.rel_steps &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stepper_motor::RelativeMove_<ContainerAllocator1> & lhs, const ::stepper_motor::RelativeMove_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stepper_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stepper_motor::RelativeMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stepper_motor::RelativeMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_motor::RelativeMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stepper_motor::RelativeMove_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_motor::RelativeMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stepper_motor::RelativeMove_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stepper_motor::RelativeMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00a9380c301e11f69986dac3c6b953bd";
  }

  static const char* value(const ::stepper_motor::RelativeMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00a9380c301e11f6ULL;
  static const uint64_t static_value2 = 0x9986dac3c6b953bdULL;
};

template<class ContainerAllocator>
struct DataType< ::stepper_motor::RelativeMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stepper_motor/RelativeMove";
  }

  static const char* value(const ::stepper_motor::RelativeMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stepper_motor::RelativeMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int64 rel_steps\n"
"int64 speed\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::stepper_motor::RelativeMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stepper_motor::RelativeMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rel_steps);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelativeMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stepper_motor::RelativeMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stepper_motor::RelativeMove_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rel_steps: ";
    Printer<int64_t>::stream(s, indent + "  ", v.rel_steps);
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEPPER_MOTOR_MESSAGE_RELATIVEMOVE_H
